# Permissões para que o GITHUB_TOKEN possa escrever no repositório
permissions:
  contents: write  # para git push
  pages: write     # se você usar o deploy Pages oficial
  id-token: write

name: Build & Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout e já mantém as credenciais para poder push
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # garante que o GITHUB_TOKEN vai servir para fazer git push

      # 2) Configura Ruby (necessário para Jekyll)
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      # 3) Build do site Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "."           
          destination: "docs"   
          future: true          
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # 4) Commit & push do site compilado
      - name: Commit compiled site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy site (GitHub Actions)" || echo "No changes to commit"
          git push origin main
